-- GOOD NEWS 1.0 – SUPABASE SETUP
-- Einmal komplett in Supabase → SQL Editor ausführen.

-- 1) Tabelle
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_date date not null,
  published_time time not null default '12:00',
  publish_at timestamptz not null default now(),
  category text not null check (char_length(category) <= 40),
  story_key text check (story_key is null or char_length(story_key) <= 80),
  title text not null check (char_length(title) <= 180),
  summary text not null check (char_length(summary) <= 1800),
  context_text text check (context_text is null or char_length(context_text) <= 1400),
  status text not null default 'draft' check (status in ('draft','published')),
  priority text not null default 'normal' check (priority in ('normal','top')),
  priority_rank int not null default 0 check (priority_rank in (0,1)),
  image_url text,
  image_path text,
  image_credit text,
  sources jsonb not null default '[]'::jsonb
);

create index if not exists news_public_feed_idx
on public.news (status, publish_at desc);

create index if not exists news_story_idx
on public.news (story_key);

alter table public.news enable row level security;

-- 2) Rechte: Besucher nur SELECT, eingeloggte Redaktion SELECT/INSERT/UPDATE/DELETE
revoke all on table public.news from anon, authenticated;
grant select on table public.news to anon;
grant select, insert, update, delete on table public.news to authenticated;

drop policy if exists "Public reads published news" on public.news;
create policy "Public reads published news"
on public.news for select
to anon
using (status = 'published' and publish_at <= now());

drop policy if exists "Editors read all news" on public.news;
create policy "Editors read all news"
on public.news for select
to authenticated
using (true);

drop policy if exists "Editors insert news" on public.news;
create policy "Editors insert news"
on public.news for insert
to authenticated
with check (true);

drop policy if exists "Editors update news" on public.news;
create policy "Editors update news"
on public.news for update
to authenticated
using (true)
with check (true);

drop policy if exists "Editors delete news" on public.news;
create policy "Editors delete news"
on public.news for delete
to authenticated
using (true);

-- 3) Sequenzrechte für Identity-Spalte
grant usage, select on sequence public.news_id_seq to authenticated;

-- 4) Öffentlicher Storage-Bucket für Nachrichtenbilder
insert into storage.buckets (id, name, public)
values ('news-images', 'news-images', true)
on conflict (id) do update set public = true;

-- Öffentlicher Lesezugriff für Bilder
drop policy if exists "Public reads news images" on storage.objects;
create policy "Public reads news images"
on storage.objects for select
to public
using (bucket_id = 'news-images');

-- Nur eingeloggte Redakteure dürfen Bilder hochladen/ändern/löschen.
drop policy if exists "Editors upload news images" on storage.objects;
create policy "Editors upload news images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'news-images');

drop policy if exists "Editors update news images" on storage.objects;
create policy "Editors update news images"
on storage.objects for update
to authenticated
using (bucket_id = 'news-images')
with check (bucket_id = 'news-images');

drop policy if exists "Editors delete news images" on storage.objects;
create policy "Editors delete news images"
on storage.objects for delete
to authenticated
using (bucket_id = 'news-images');

-- WICHTIG:
-- Lege unter Authentication zunächst DEIN eigenes Konto an.
-- Deaktiviere danach öffentliche Neuanmeldungen/Signups im Supabase-Dashboard,
-- weil in dieser App jeder authentifizierte Benutzer als Redakteur behandelt wird.


-- 5) App-/Design-Einstellungen
create table if not exists public.app_settings (
  id int primary key default 1 check (id = 1),
  updated_at timestamptz not null default now(),
  app_name text not null default 'Good News',
  logo_url text,
  logo_path text,
  background_color text not null default '#0e0e10',
  text_color text not null default '#f5f5f5',
  accent_color text not null default '#ffffff',
  title_size text not null default 'normal' check (title_size in ('compact','normal','large')),
  corner_style text not null default 'soft' check (corner_style in ('square','soft','round')),
  image_mode text not null default 'full' check (image_mode in ('full','top','hidden')),
  overlay_strength int not null default 65 check (overlay_strength between 0 and 90),
  show_category boolean not null default true,
  show_date boolean not null default true,
  show_sources boolean not null default true,
  show_counter boolean not null default true
);

insert into public.app_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.app_settings enable row level security;

revoke all on table public.app_settings from anon, authenticated;
grant select on table public.app_settings to anon, authenticated;
grant update on table public.app_settings to authenticated;

drop policy if exists "Public reads app settings" on public.app_settings;
create policy "Public reads app settings"
on public.app_settings for select
to anon, authenticated
using (true);

drop policy if exists "Editors update app settings" on public.app_settings;
create policy "Editors update app settings"
on public.app_settings for update
to authenticated
using (id = 1)
with check (id = 1);
