-- GOOD NEWS 1.0 – SUPABASE SETUP
-- Einmal komplett in Supabase → SQL Editor ausführen.

-- 1) Tabelle
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_date date not null,
  published_time time not null default '12:00',
  publish_at timestamptz not null default now(),
  category text not null check (char_length(category) <= 40),
  story_key text check (story_key is null or char_length(story_key) <= 80),
  title text not null check (char_length(title) <= 180),
  summary text not null check (char_length(summary) <= 1800),
  context_text text check (context_text is null or char_length(context_text) <= 1400),
  status text not null default 'draft' check (status in ('draft','published')),
  priority text not null default 'normal' check (priority in ('normal','top')),
  priority_rank int not null default 0 check (priority_rank in (0,1)),
  image_url text,
  image_path text,
  image_credit text,
  sources jsonb not null default '[]'::jsonb
);

create index if not exists news_public_feed_idx
on public.news (status, publish_at desc);

create index if not exists news_story_idx
on public.news (story_key);

alter table public.news enable row level security;

-- 2) Rechte: Besucher nur SELECT, eingeloggte Redaktion SELECT/INSERT/UPDATE/DELETE
revoke all on table public.news from anon, authenticated;
grant select on table public.news to anon;
grant select, insert, update, delete on table public.news to authenticated;

drop policy if exists "Public reads published news" on public.news;
create policy "Public reads published news"
on public.news for select
to anon
using (status = 'published' and publish_at <= now());

drop policy if exists "Editors read all news" on public.news;
create policy "Editors read all news"
on public.news for select
to authenticated
using (true);

drop policy if exists "Editors insert news" on public.news;
create policy "Editors insert news"
on public.news for insert
to authenticated
with check (true);

drop policy if exists "Editors update news" on public.news;
create policy "Editors update news"
on public.news for update
to authenticated
using (true)
with check (true);

drop policy if exists "Editors delete news" on public.news;
create policy "Editors delete news"
on public.news for delete
to authenticated
using (true);

-- 3) Sequenzrechte für Identity-Spalte
grant usage, select on sequence public.news_id_seq to authenticated;

-- 4) Öffentlicher Storage-Bucket für Nachrichtenbilder
insert into storage.buckets (id, name, public)
values ('news-images', 'news-images', true)
on conflict (id) do update set public = true;

-- Öffentlicher Lesezugriff für Bilder
drop policy if exists "Public reads news images" on storage.objects;
create policy "Public reads news images"
on storage.objects for select
to public
using (bucket_id = 'news-images');

-- Nur eingeloggte Redakteure dürfen Bilder hochladen/ändern/löschen.
drop policy if exists "Editors upload news images" on storage.objects;
create policy "Editors upload news images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'news-images');

drop policy if exists "Editors update news images" on storage.objects;
create policy "Editors update news images"
on storage.objects for update
to authenticated
using (bucket_id = 'news-images')
with check (bucket_id = 'news-images');

drop policy if exists "Editors delete news images" on storage.objects;
create policy "Editors delete news images"
on storage.objects for delete
to authenticated
using (bucket_id = 'news-images');

-- WICHTIG:
-- Lege unter Authentication zunächst DEIN eigenes Konto an.
-- Deaktiviere danach öffentliche Neuanmeldungen/Signups im Supabase-Dashboard,
-- weil in dieser App jeder authentifizierte Benutzer als Redakteur behandelt wird.


-- 5) App-/Design-Einstellungen
create table if not exists public.app_settings (
  id int primary key default 1 check (id = 1),
  updated_at timestamptz not null default now(),
  app_name text not null default 'Good News',
  logo_url text,
  logo_path text,
  background_color text not null default '#0e0e10',
  text_color text not null default '#f5f5f5',
  accent_color text not null default '#ffffff',
  title_size text not null default 'normal' check (title_size in ('compact','normal','large')),
  corner_style text not null default 'soft' check (corner_style in ('square','soft','round')),
  image_mode text not null default 'full' check (image_mode in ('full','top','hidden')),
  overlay_strength int not null default 65 check (overlay_strength between 0 and 90),
  show_category boolean not null default true,
  show_date boolean not null default true,
  show_sources boolean not null default true,
  show_counter boolean not null default true
);

insert into public.app_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.app_settings enable row level security;

revoke all on table public.app_settings from anon, authenticated;
grant select on table public.app_settings to anon, authenticated;
grant update on table public.app_settings to authenticated;

drop policy if exists "Public reads app settings" on public.app_settings;
create policy "Public reads app settings"
on public.app_settings for select
to anon, authenticated
using (true);

drop policy if exists "Editors update app settings" on public.app_settings;
create policy "Editors update app settings"
on public.app_settings for update
to authenticated
using (id = 1)
with check (id = 1);



-- Good News 3.1 – Bildquelle/Lizenz kompakt im Slide
alter table public.news add column if not exists image_license text;
alter table public.news add column if not exists image_source_url text;
alter table public.news add column if not exists image_kind text not null default 'photo';
alter table public.news add column if not exists is_symbol_image boolean not null default false;
update public.news set is_symbol_image = true where image_kind = 'symbol' and is_symbol_image = false;

-- 8) Entwürfe - Dreier (Good News 3.0)
-- Empfangsbox für automatisch erzeugte Dreier. Anonyme Clients dürfen NUR einreichen,
-- lesen/prüfen/übernehmen kann ausschließlich die eingeloggte Redaktion.
create table if not exists public.triple_drafts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  draft_date date not null,
  source_label text not null default 'ChatGPT',
  status text not null default 'new' check (status in ('new','imported','rejected')),
  payload jsonb not null
);

create index if not exists triple_drafts_status_idx
on public.triple_drafts (status, created_at desc);

alter table public.triple_drafts enable row level security;
revoke all on table public.triple_drafts from anon, authenticated;
grant insert on table public.triple_drafts to anon;
grant select, insert, update, delete on table public.triple_drafts to authenticated;
grant usage, select on sequence public.triple_drafts_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit triple drafts" on public.triple_drafts;
create policy "Anyone can submit triple drafts"
on public.triple_drafts for insert
to anon
with check (status = 'new');

drop policy if exists "Editors manage triple drafts" on public.triple_drafts;
create policy "Editors manage triple drafts"
on public.triple_drafts for all
to authenticated
using (true)
with check (true);

-- Falls diese Good-News-Dreier-Felder in einem älteren Projekt noch fehlen:
alter table public.news add column if not exists daily_slot text not null default 'none';
alter table public.news add column if not exists years_ago int;
alter table public.news add column if not exists feel_good_text text;
alter table public.news add column if not exists image_fit text not null default 'cover';
alter table public.news add column if not exists image_zoom numeric not null default 1;
alter table public.news add column if not exists image_x numeric not null default 50;
alter table public.news add column if not exists image_y numeric not null default 50;


-- Good News: anonyme Nutzungsstatistik (nur im Adminbereich lesbar)
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('active','favorite','share')),
  visitor_id text not null check (char_length(visitor_id) between 8 and 120),
  news_id bigint null references public.news(id) on delete set null
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_type_created_idx on public.analytics_events (event_type, created_at desc);
create index if not exists analytics_events_visitor_created_idx on public.analytics_events (visitor_id, created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "public can add analytics events" on public.analytics_events;
create policy "public can add analytics events"
on public.analytics_events
for insert
to anon, authenticated
with check (event_type in ('active','favorite','share'));

drop policy if exists "authenticated can read analytics events" on public.analytics_events;
create policy "authenticated can read analytics events"
on public.analytics_events
for select
to authenticated
using (true);

create or replace function public.get_analytics_summary()
returns table (
  active_today bigint,
  active_7d bigint,
  active_30d bigint,
  favorites_today bigint,
  favorites_7d bigint,
  favorites_30d bigint,
  shares_today bigint,
  shares_7d bigint,
  shares_30d bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  with bounds as (
    select ((date_trunc('day', now() at time zone 'Europe/Berlin')) at time zone 'Europe/Berlin') as today_start
  )
  select
    count(distinct visitor_id) filter (where event_type='active' and created_at >= b.today_start)::bigint,
    count(distinct visitor_id) filter (where event_type='active' and created_at >= now() - interval '7 days')::bigint,
    count(distinct visitor_id) filter (where event_type='active' and created_at >= now() - interval '30 days')::bigint,
    count(*) filter (where event_type='favorite' and created_at >= b.today_start)::bigint,
    count(*) filter (where event_type='favorite' and created_at >= now() - interval '7 days')::bigint,
    count(*) filter (where event_type='favorite' and created_at >= now() - interval '30 days')::bigint,
    count(*) filter (where event_type='share' and created_at >= b.today_start)::bigint,
    count(*) filter (where event_type='share' and created_at >= now() - interval '7 days')::bigint,
    count(*) filter (where event_type='share' and created_at >= now() - interval '30 days')::bigint
  from public.analytics_events, bounds b
  group by b.today_start;
$$;

revoke all on function public.get_analytics_summary() from public;
grant execute on function public.get_analytics_summary() to authenticated;

-- Good News: freiwillige Namensnennung bei Leser-Einsendungen
alter table if exists public.submissions
  add column if not exists publish_submitter_name boolean not null default false;

alter table if exists public.news
  add column if not exists byline_name text,
  add column if not exists byline_visible boolean not null default false;

do $$
begin
  if to_regclass('public.news') is not null
     and not exists (select 1 from pg_constraint where conname='news_byline_name_length') then
    alter table public.news
      add constraint news_byline_name_length
      check (byline_name is null or char_length(byline_name) <= 80);
  end if;
end $$;


-- =========================================================
-- GOOD NEWS RELEASE SECURITY – Rollenbasierte Redaktion
-- =========================================================
-- Normale angemeldete Nutzer sind KEINE Redakteure.
-- Nur Nutzer mit role='admin' in public.user_roles erhalten Redaktionsrechte.

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','user')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

revoke all on table public.user_roles from anon, authenticated;
grant select on table public.user_roles to authenticated;

drop policy if exists "Users read own role" on public.user_roles;
create policy "Users read own role"
on public.user_roles for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

-- SECURITY DEFINER nicht pauschal für PUBLIC ausführbar lassen.
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- News
drop policy if exists "Editors read all news" on public.news;
create policy "Editors read all news"
on public.news for select to authenticated
using (public.is_admin());

drop policy if exists "Editors insert news" on public.news;
create policy "Editors insert news"
on public.news for insert to authenticated
with check (public.is_admin());

drop policy if exists "Editors update news" on public.news;
create policy "Editors update news"
on public.news for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Editors delete news" on public.news;
create policy "Editors delete news"
on public.news for delete to authenticated
using (public.is_admin());

-- Angemeldete normale Nutzer dürfen veröffentlichte News weiterhin lesen.
drop policy if exists "Authenticated users read published news" on public.news;
create policy "Authenticated users read published news"
on public.news for select to authenticated
using (status='published' and publish_at<=now());

-- Storage
drop policy if exists "Editors upload news images" on storage.objects;
create policy "Editors upload news images"
on storage.objects for insert to authenticated
with check (bucket_id='news-images' and public.is_admin());

drop policy if exists "Editors update news images" on storage.objects;
create policy "Editors update news images"
on storage.objects for update to authenticated
using (bucket_id='news-images' and public.is_admin())
with check (bucket_id='news-images' and public.is_admin());

drop policy if exists "Editors delete news images" on storage.objects;
create policy "Editors delete news images"
on storage.objects for delete to authenticated
using (bucket_id='news-images' and public.is_admin());

-- App-Einstellungen
drop policy if exists "Editors update app settings" on public.app_settings;
create policy "Editors update app settings"
on public.app_settings for update to authenticated
using (id=1 and public.is_admin())
with check (id=1 and public.is_admin());

-- Dreier-Entwürfe
drop policy if exists "Editors manage triple drafts" on public.triple_drafts;
create policy "Editors manage triple drafts"
on public.triple_drafts for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Analytics nur Redaktion
drop policy if exists "authenticated can read analytics events" on public.analytics_events;
drop policy if exists "Editors read analytics events" on public.analytics_events;
create policy "Editors read analytics events"
on public.analytics_events for select to authenticated
using (public.is_admin());

-- WICHTIG:
-- Nach dem Erstellen deines Redaktionskontos einmalig im SQL Editor ausführen:
-- insert into public.user_roles (user_id, role)
-- select id, 'admin' from auth.users where email = 'DEINE-EMAIL'
-- on conflict (user_id) do update set role='admin';


-- Rechtliche Angaben, öffentlich lesbar über app_settings; nur Admins dürfen sie ändern.
alter table public.app_settings add column if not exists legal_settings jsonb not null default '{}'::jsonb;

-- Push-Abonnements
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.push_subscriptions enable row level security;


-- Fehlermeldungen zu Good-News-Beiträgen
create table if not exists public.news_reports (
  id bigint generated by default as identity primary key,
  news_id bigint not null references public.news(id) on delete cascade,
  reporter_user_id uuid null references auth.users(id) on delete set null,
  report_type text not null check (report_type in ('content','source','image','spelling','other')),
  comment text null check (char_length(comment) <= 1000),
  status text not null default 'new' check (status in ('new','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.news_reports enable row level security;
grant insert on public.news_reports to anon, authenticated;
grant select, update on public.news_reports to authenticated;
grant usage, select on sequence public.news_reports_id_seq to anon, authenticated;
drop policy if exists "Anyone can report news" on public.news_reports;
create policy "Anyone can report news" on public.news_reports for insert to anon, authenticated with check (reporter_user_id is null or reporter_user_id = (select auth.uid()));
drop policy if exists "Admins read reports" on public.news_reports;
create policy "Admins read reports" on public.news_reports for select to authenticated using (public.is_admin());
drop policy if exists "Admins update reports" on public.news_reports;
create policy "Admins update reports" on public.news_reports for update to authenticated using (public.is_admin()) with check (public.is_admin());


-- =========================================================
-- GOOD NEWS BUILD 40 – Release-Härtung
-- =========================================================
-- Trigger-Funktionen dürfen nicht direkt über die Data API aufrufbar sein.
revoke execute on function public.create_default_user_role() from public, anon, authenticated;
-- is_admin() wird von RLS-Policies für angemeldete Nutzer benötigt, aber nicht anonym.
revoke execute on function public.is_admin() from anon;

-- =========================================================
-- GOOD NEWS BUILD 43 – Push-Filter pro Gerät
-- =========================================================
alter table public.push_subscriptions
  add column if not exists notify_morning boolean not null default true,
  add column if not exists notify_evening boolean not null default true,
  add column if not exists notify_categories text[] not null default array[
    'Was war....',
    'Tiere',
    'Sport',
    'Wirtschaft & Politik',
    'Fortschritt, Medizin & Technologie',
    'Kultur/Natur'
  ]::text[];


-- =========================================================
-- GOOD NEWS BUILD 44 – Push-Abos pro Installation entdoppeln
-- =========================================================
alter table public.push_subscriptions
  add column if not exists device_key text null;
create index if not exists push_subscriptions_device_key_idx
  on public.push_subscriptions(device_key);
